version: '3'
services:
  server: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /server/node_modules
      - ./:/server
    environment:
      - DB_KEY=${DB_KEY}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "6000:6000"